name: CI/CD Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run ESLint & Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js & Setup Cache for Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn lint

      - name: Run Prettier
        run: yarn format --check

  type-check:
    name: TypeScript Type Checking
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js & Setup Cache for Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install

      - name: Run TypeScript Type Checking
        run: yarn type-check

  deploy:
    name: Deploy to Vercel
    needs: type-check
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: yarn global add vercel

      - name: Deploy to Vercel
        run: vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
